import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from '@/providers/react-query';
import SuggestionProvider from '@/context/suggestion-provider';
import SearchProvider from '@/context/search-provider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryProvider>
            <SuggestionProvider>
                <SearchProvider>
                    <html lang="en">
                        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                            <main className="h-screen">{children}</main>
                        </body>
                    </html>
                </SearchProvider>
            </SuggestionProvider>
        </ReactQueryProvider>
    );
}
